version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    command: mongod --port 27017
    ports:
      - "27017:27017"
    container_name: javatechiemongodb
  spring:
    build: "./"
    container_name: spring-composed
    ports:
      - "8080:8080"
    depends_on:
      - mongo
